/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-12 23:24:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>관리자 정보 - 관리자페이지</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body,td,th {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	color: #606060;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("	margin-left: 0px;\r\n");
      out.write("	margin-top: 0px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("	<tr><td>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top_menu.jsp", out, true);
      out.write("</td></tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\" height=\"100%\" valign=middle><br>\r\n");
      out.write("			<table width=\"30%\" border=\"1\" cellspacing=\"0\" cellpadding=\"3\" bgcolor=\"#FFCC66\" bordercolor=\"#FFFFFF\" bordercolorlight=\"#000000\">\r\n");
      out.write("				<tr> \r\n");
      out.write("					<td height=40 align=\"center\" style=\"font-size: 15px;\"><b>관리자 [등록][수정]</b>\r\n");
      out.write("					</b></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table><br>\r\n");
      out.write("			<table width=\"60%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<form name=\"frm\" method=\"post\" >\r\n");
      out.write("					<td><table width=\"100%\" border=\"0\" cellpadding=\"6\" cellspacing=\"1\" bgcolor=\"DDDDDD\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td width=\"30%\" align=\"center\" bgcolor=\"EcECEC\"><strong>관리자아이디</strong></td>\r\n");
      out.write("								<td bgcolor=\"ffffff\"><input name=\"adminid\" type=\"text\" value=\"\"  style=\"width:150; height:18; padding:2; border:1 solid slategray\" size=\"120\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td width=\"30%\" align=\"center\" bgcolor=\"EcECEC\"><strong>관리자비밀번호</strong></td>\r\n");
      out.write("								<td bgcolor=\"ffffff\"><input name=\"adminpass\" type=\"text\" value=\"\"  style=\"width:150; height:18; padding:2; border:1 solid slategray\" size=\"120\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td width=\"30%\" align=\"center\" bgcolor=\"EcECEC\"><strong>관리자등급</strong></td>\r\n");
      out.write("								<td bgcolor=\"ffffff\"><select name=\"rate\">\r\n");
      out.write("								<option value=\"1\">1등급</option>\r\n");
      out.write("								<option value=\"2\">2등급</option>\r\n");
      out.write("								<option value=\"3\">3등급</option>\r\n");
      out.write("								<option value=\"4\">4등급</option>\r\n");
      out.write("								</select>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</td>\r\n");
      out.write("					</form>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table><br>\r\n");
      out.write("			<table width=\"60%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=center>\r\n");
      out.write("					[수정]&nbsp;[등록]&nbsp;[취소]</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>			\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
