/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-12 03:34:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>관리자 페이지</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<style type=\"text/css\"> \n");
      out.write("<!-- \n");
      out.write("body,td,tr,table{font-size:9pt; font-family:tahoma;color:#666666;line-height:160%;} \n");
      out.write("\n");
      out.write("A:link {font-family:tahoma;font-size:9pt;color:#666666;text-decoration:none;} \n");
      out.write("A:visited {font-family:tahoma;font-size:9pt;color:#666666;text-decoration:none;} \n");
      out.write("A:active {font-family:tahoma;font-size:9pt;color:#666666;text-decoration:none;} \n");
      out.write("A:hover {font-family:tahoma;font-size:9pt;color:#009900;text-decoration:underline;} \n");
      out.write("--> \n");
      out.write("</style> \n");
      out.write("</head>\n");
      out.write("<body text=\"#000000\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n");
      out.write("<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("<form name=\"frm\" method=\"post\" >\n");
      out.write("  <tr>\n");
      out.write("    <td><table width=\"100%\" height=\"420\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"img/bg.gif\">\n");
      out.write("        <tr> \n");
      out.write("          <td>&nbsp;</td>\n");
      out.write("          <td width=\"617\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("              <tr> \n");
      out.write("                <td colspan=\"4\"><img src=\"img/admin_img01.gif\" width=\"617\" height=\"60\"></td>\n");
      out.write("              </tr>\n");
      out.write("              <tr> \n");
      out.write("                <td width=\"9\"><img src=\"img/admin_img02.gif\" width=\"9\" height=\"314\"></td>\n");
      out.write("                <td width=\"219\"><img src=\"img/admin_img03.gif\" width=\"219\" height=\"314\"></td>\n");
      out.write("                <td width=\"381\" align=\"center\" bgcolor=\"#FFFFFF\"><table width=\"332\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <tr> \n");
      out.write("                      <td>&nbsp;</td>\n");
      out.write("                      <!-- 메일주소 들어가는 곳 -->\n");
      out.write("                      <td><strong><u>websnet.net</u></strong></td>\n");
      out.write("                      <!--// 메일주소 들어가는 곳 -->\n");
      out.write("                      <td>&nbsp;</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr> \n");
      out.write("                      <td>&nbsp;</td>\n");
      out.write("                      <td height=\"65\" valign=\"top\"><img src=\"img/admin_img13.gif\" width=\"154\" height=\"26\"></td>\n");
      out.write("                      <td>&nbsp;</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr> \n");
      out.write("                      <td>&nbsp;</td>\n");
      out.write("                      <td style=\"padding:0 0 10 0;\">websnet.net의 관리자페이지 입니다.<br> \n");
      out.write("											<strong>전체적인 게시판 관리</strong>를 하실 수 있습니다.<BR> \n");
      out.write("                        Internet Explorer4.0 이상에 최적화 되어 있습니다.</td>\n");
      out.write("                      <td>&nbsp;</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr> \n");
      out.write("                      <td width=\"12\"><img src=\"img/admin_img06.gif\" width=\"12\" height=\"107\"></td>\n");
      out.write("                      <td width=\"308\" align=\"center\" background=\"img/admin_img07.gif\"> \n");
      out.write("                        <!-- 도메인, 관리계정, 비밀번호 -->\n");
      out.write("                        <table width=\"275\" height=\"63\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                          <tr> \n");
      out.write("                            <td><img src=\"img/admin_img09.gif\" alt=\"도메인\" width=\"64\" height=\"19\" align=\"absmiddle\"> \n");
      out.write("                              <input name=\"domain\" type=\"text\" style=\"width:140px;\" value=\"websnet.net\" readonly></td>\n");
      out.write("                            <td width=\"61\" rowspan=\"3\"><input type='image' src=\"img/admin_img12.gif\" alt=\"connect\" value=\"submit\" width=\"61\" height=\"63\" border=\"0\" onfocus=blur()></a></td>\n");
      out.write("                          </tr>\n");
      out.write("                          <tr> \n");
      out.write("                            <td><img src=\"img/admin_img10.gif\" alt=\"관리계정\" width=\"64\" height=\"19\" align=\"absmiddle\"> \n");
      out.write("                              <input name=\"adminid\" type=\"text\" tabindex=\"1\" style=\"width:140px;\"></td>\n");
      out.write("                          </tr>\n");
      out.write("                          <tr> \n");
      out.write("                            <td><img src=\"img/admin_img11.gif\" alt=\"비밀번호\" width=\"64\" height=\"19\" align=\"absmiddle\"> \n");
      out.write("                              <input name=\"adminpass\" type=\"password\" tabindex=\"2\" style=\"width:140px;\"></td>\n");
      out.write("                          </tr>\n");
      out.write("                        </table>\n");
      out.write("                        <!--// 도메인, 관리계정, 비밀번호 -->\n");
      out.write("                      </td>\n");
      out.write("                      <td width=\"12\"><img src=\"img/admin_img08.gif\" width=\"12\" height=\"107\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table></td>\n");
      out.write("                <td width=\"8\"><img src=\"img/admin_img04.gif\" width=\"8\" height=\"314\"></td>\n");
      out.write("              </tr>\n");
      out.write("              <tr> \n");
      out.write("                <td colspan=\"4\"><img src=\"img/admin_img05.gif\" width=\"617\" height=\"46\"></td>\n");
      out.write("              </tr>\n");
      out.write("            </table></td>\n");
      out.write("          <td>&nbsp;</td>\n");
      out.write("        </tr>\n");
      out.write("      </table></td>\n");
      out.write("  </tr>\n");
      out.write("</form>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
