/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-19 02:34:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>공지사항 관리 - 관리자페이지</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<style type=\"text/css\"> \n");
      out.write("<!-- \n");
      out.write("body,td,tr,table{font-size:9pt; font-family:tahoma;color:#666666;line-height:160%;} \n");
      out.write("\n");
      out.write("A:link {font-family:tahoma;font-size:9pt;color:#666666;text-decoration:none;} \n");
      out.write("A:visited {font-family:tahoma;font-size:9pt;color:#666666;text-decoration:none;} \n");
      out.write("A:active {font-family:tahoma;font-size:9pt;color:#666666;text-decoration:none;} \n");
      out.write("A:hover {font-family:tahoma;font-size:9pt;color:#009900;text-decoration:underline;} \n");
      out.write("--> \n");
      out.write("</style> \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr><td>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top_menu.jsp", out, true);
      out.write("</td></tr>\n");
      out.write("	<tr>\n");
      out.write("		<td align=\"center\" height=\"100%\" valign=middle><br>\n");
      out.write("			<table width=\"30%\" border=\"1\" cellspacing=\"0\" cellpadding=\"3\" bgcolor=\"#FFCC66\" bordercolor=\"#FFFFFF\" bordercolorlight=\"#000000\">\n");
      out.write("				<tr> \n");
      out.write("					<td height=40 align=\"center\" style=\"font-size: 15px;\"><b>공지사항 리스트</b></a>\n");
      out.write("					</b></td>\n");
      out.write("				</tr>\n");
      out.write("			</table><br>\n");
      out.write("			<table width=\"80%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("				<tr>\n");
      out.write("                    <td height=\"20\">* 총 등록수 : <font color=red>33</font> 건</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td><table width=\"100%\" border=\"0\" cellpadding=\"6\" cellspacing=\"1\" bgcolor=\"DDDDDD\">\n");
      out.write("                      <tr bgcolor=\"EcECEC\">\n");
      out.write("                        <td width=\"15%\" align=\"center\" bgcolor=\"EcECEC\"><strong>번호</strong></td>\n");
      out.write("						<td align=\"center\" bgcolor=\"EcECEC\"><strong>제목</strong></td>\n");
      out.write("                        <td width=\"20%\" align=\"center\"><strong>접수일</strong></td>\n");
      out.write("                        <td width=\"10%\" align=\"center\"><strong>조회수</strong></td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <td align=\"center\" bgcolor=\"#FFFFFF\">1</td>\n");
      out.write("                        <td bgcolor=\"#FFFFFF\"><a href=\"\" class=\"unnamed1\">안녕하세요</a></td>\n");
      out.write("                        <td align=\"center\" bgcolor=\"#FFFFFF\">2007-11-11</td>\n");
      out.write("						<td align=\"center\" bgcolor=\"#FFFFFF\">3</td>\n");
      out.write("                      </tr>\n");
      out.write("	                     <tr>\n");
      out.write("                        <td height=\"35\" colspan=\"10\" align=\"center\" bgcolor=\"#FFFFFF\">[1][2][3]</td>\n");
      out.write("                      </tr>\n");
      out.write("					<form action=\"notice.jsp\" method=\"post\" name=\"b_search\">\n");
      out.write("                      <tr>\n");
      out.write("                        <td colspan=\"10\" align=\"center\" bgcolor=\"#FFFFFF\"><table width=\"610\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                              <td width=80% height=\"30\" colspan=\"2\" align=\"right\">\n");
      out.write("								<select name=\"search\" class=\"textfield\">\n");
      out.write("									<option >제목</option>\n");
      out.write("								</select>\n");
      out.write("								<input name=\"key\" type=\"text\" class=\"textfield\" size=\"30\" value=\"\"></td>\n");
      out.write("                              <td width=20% align=\"right\"><a href=\"\"><b>[검색]</b></a>  &nbsp;<a href=\"\"><b>[글쓰기]</b></a></td>\n");
      out.write("                            </tr>\n");
      out.write("									\n");
      out.write("                        </table></td>\n");
      out.write("                      </tr>\n");
      out.write("                    </table>\n");
      out.write("                   </td>\n");
      out.write("               </tr>\n");
      out.write("           </table>\n");
      out.write("       </td>\n");
      out.write("    </tr>\n");
      out.write("</table>\n");
      out.write("                   \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
