/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-19 02:34:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_005fmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>관리자</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("\n");
      out.write("<style type=\"text/css\"> \n");
      out.write("<!-- \n");
      out.write("body,td,tr,table{font-size:9pt; font-family:tahoma;color:#000000;line-height:160%;} \n");
      out.write("\n");
      out.write("A:link {font-family:tahoma;font-size:9pt;color:#000000;text-decoration:none;} \n");
      out.write("A:visited {font-family:tahoma;font-size:9pt;color:#000000;text-decoration:none;} \n");
      out.write("A:active {font-family:tahoma;font-size:9pt;color:#000000;text-decoration:none;} \n");
      out.write("A:hover {font-family:tahoma;font-size:9pt;color:#000000;text-decoration:underline;} \n");
      out.write("--> \n");
      out.write("</style> \n");
      out.write("</HEAD>\n");
      out.write("<BODY topmargin=0 leftmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n");
      out.write("  <TABLE WIDTH=100% height=30 border=0 bgcolor=\"#FFCC66\">\n");
      out.write("    <TR> \n");
      out.write("			<TD width=\"20\"></TD>\n");
      out.write("			<td width=\"100\"> \n");
      out.write("        <p><a href=\"notice_list.jsp\">[공지사항 관리]</a></p>\n");
      out.write("      </td>\n");
      out.write("			<TD width=\"100\"> \n");
      out.write("        <P><a href=\"board_list.jsp\">[게시판 관리]</a></P>\n");
      out.write("      </TD>\n");
      out.write("			<TD width=\"100\"> \n");
      out.write("        <P><a href=\"member_list.jsp\">[회원관리]</a></P>\n");
      out.write("      </TD>\n");
      out.write("			<TD width=\"100\"> \n");
      out.write("        <P><a href=\"pds_list.jsp\">[자료실 관리]</a></P>\n");
      out.write("      </TD>\n");
      out.write("			<TD width=\"100\"> \n");
      out.write("        <P><a href=\"guest_list.jsp\">[방명록 관리]</a></P>\n");
      out.write("      </TD>\n");
      out.write("			<TD width=\"100\"> \n");
      out.write("        	<P><a href=\"admin.jsp\">[관리자 관리]</a></P>\n");
      out.write("      </TD>\n");
      out.write("      <TD width=\"100\"> \n");
      out.write("        <P><a href=\"logout.jsp\">로그아웃</a></P>\n");
      out.write("      </TD>\n");
      out.write("    </TR>\n");
      out.write("  </TABLE>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
