/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-27 05:57:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userinfo_005finsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원등록(이메일 본인 인증)</title>\r\n");
      out.write("<STYLE TYPE=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body { font-family: 돋움, Verdana; font-size: 9pt}\r\n");
      out.write("td   { font-family: 돋움, Verdana; font-size: 9pt; text-decoration: none; color: #000000; BACKGROUND-POSITION: left top; BACKGROUND-REPEAT: no-repeat;}\r\n");
      out.write("-->\r\n");
      out.write(".formbox {\r\n");
      out.write("	BACKGROUND-COLOR: #F0F0F0; FONT-FAMILY: \"Verdana\", \"Arial\", \"Helvetica\", \"돋움\"; FONT-SIZE:9pt\r\n");
      out.write("} \r\n");
      out.write("--->\r\n");
      out.write("</STYLE>\r\n");
      out.write("<script>\r\n");
      out.write("	function send(){\r\n");
      out.write("		mform.submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function emailcheck(email1, email2){\r\n");
      out.write("	    // 유효성 검사\r\n");
      out.write("		if(!mform.email1.value || !mform.email2.value){ \r\n");
      out.write("			alert(\"이메일을 입력하세요\");\r\n");
      out.write("			mform.email1.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}else{\r\n");
      out.write("			if(mform.email1.value){\r\n");
      out.write("				if(mform.email2.value==0){\r\n");
      out.write("					// 직접입력\r\n");
      out.write("					if(mform.email1.value.indexOf(\"@\")==-1){\r\n");
      out.write("						alert(\"이메일 형식이 맞지 않습니다\");\r\n");
      out.write("						mform.email1.focus();\r\n");
      out.write("						return false;\r\n");
      out.write("					}\r\n");
      out.write("				}else{\r\n");
      out.write("					// 선택입력\r\n");
      out.write("					if(mform.email1.value.indexOf(\"@\")!=-1){\r\n");
      out.write("						alert(\"이메일 형식이 맞지 않습니다\");\r\n");
      out.write("						mform.email1.focus();\r\n");
      out.write("						return false;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	    // 인증을 위해 새창으로 이동\r\n");
      out.write("		var url=\"userinfo_insert_email.jsp?email1=\"+email1+\"&email2=\"+email2;\r\n");
      out.write("		open(url,\"emailwindow\", \"statusbar=no, scrollbar=no, menubar=no, width=450, height=200\" );\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" LEFTMARGIN=0  TOPMARGIN=0 >\r\n");
      out.write(" \r\n");
      out.write(" <!-- 탑 메뉴 영역 삽입-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" width=\"800\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <td width=\"20%\"  bgcolor=\"#ecf1ef\" valign=\"top\" style=\"padding-left:0;\">\r\n");
      out.write("	\r\n");
      out.write("	<!--로그인 영역 삽입-->\r\n");
      out.write("\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=\"80%\" valign=\"top\">&nbsp;<img src=\"./img/title1.gif\" ><br>    \r\n");
      out.write("	<form name=\"mform\" method=\"post\" action=\"userinfo_insert_pro.jsp\">\r\n");
      out.write("	<table border=0 cellpadding=0 cellspacing=0 border=0 width=730 valign=top>\r\n");
      out.write("		<tr><td align=center><br>                            \r\n");
      out.write("			<table cellpadding=0 cellspacing=0 border=0 width=650 align=center>       \r\n");
      out.write("				<tr>\r\n");
      out.write("					<td bgcolor=\"#7AAAD5\">            \r\n");
      out.write("						<table cellpadding=0 cellspacing=0 border=0 width=100%>\r\n");
      out.write("							<tr bgcolor=#7AAAD5>\r\n");
      out.write("								<td align=left BORDER=\"0\" HSPACE=\"0\" VSPACE=\"0\"><img src=\"./img/u_b02.gif\"></td>\r\n");
      out.write("								<td align=center bgcolor=\"#7AAAD5\"><FONT COLOR=\"#FFFFFF\"><b>사용자등록&nbsp;</b><font color=black>(</font><font color=red>&nbsp;*&nbsp;</font><font color=black>표시항목은 반드시 입력하십시요.)</font></FONT></td>\r\n");
      out.write("								<td align=right BORDER=\"0\" HSPACE=\"0\" VSPACE=\"0\"><img src=\"./img/u_b03.gif\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<table cellpadding=3 cellspacing=1 border=0 width=100%>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td width=110 bgcolor=#EFF4F8>&nbsp;회원 성명<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<input type=text name=name size=16 maxlength=20 value=\"\">성명은 빈칸없이 입력하세요.\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;회원 ID<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<table cellspacing=0 cellpadding=0>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td align=absmiddle>\r\n");
      out.write("												<input type=text name=userid size=12 maxlength=16 value=\"\" style=\"width:120\">\r\n");
      out.write("											</td>\r\n");
      out.write("											<td>\r\n");
      out.write("                  								<img src=\"./img/u_bt01.gif\" hspace=2 border=0 name=img1  align=absmiddle>\r\n");
      out.write("                   								5~16자 이내의 영문이나 숫자만 가능합니다.\r\n");
      out.write("                  							</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</table>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;비밀번호<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("								<input type=password name=passwd size=8 maxlength=12 style=\"width:80\">\r\n");
      out.write("                 					6~12자 이내의 영문이나 숫자만 가능합니다.\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;비밀번호확인<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE><input type=password name=repasswd size=8 maxlength=12 value=\"\" style=\"width:80\">비밀번호 확인을 위해서 비밀번호를 한번 더 입력해주세요. </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("               					<TD BGCOLOR=\"#EFF4F8\">&nbsp;전화번호<font color=red>&nbsp;*</font></td>\r\n");
      out.write("                				<TD BGCOLOR=WHITE>\r\n");
      out.write("                  					<input type=text name=tel size=13 maxlength=13 value=\"\">\r\n");
      out.write("               					</td>\r\n");
      out.write("              				</tr>\r\n");
      out.write("              				<tr>\r\n");
      out.write("                				<TD BGCOLOR=\"#EFF4F8\">&nbsp;E-mail\r\n");
      out.write("                					<font color=red>&nbsp;</font>\r\n");
      out.write("                				</td>\r\n");
      out.write("                				<td bgcolor=WHITE valign=middle>\r\n");
      out.write("									    <input type=\"text\" name=\"email1\" maxlength=\"15\">\r\n");
      out.write("										@ <select name=\"email2\">\r\n");
      out.write("		      								<option value=\"0\">직접입력</option>\r\n");
      out.write("		      								<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("		      								<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("		      								<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("		      								<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("		  								  </select>\r\n");
      out.write("										  <input type=\"button\"  value=\"인증하기\" \r\n");
      out.write("         									onclick=\"emailcheck(mform.email1.value,mform.email2.value)\">\r\n");
      out.write("								\r\n");
      out.write("								</td>\r\n");
      out.write("              				</tr>\r\n");
      out.write("            			</table>\r\n");
      out.write("            			<table cellpadding=0 cellspacing=0 border=0 width=100%>\r\n");
      out.write("              				<tr bgcolor=#7AAAD5>\r\n");
      out.write("                				<td valign=bottom>\r\n");
      out.write("                  					<img src=\"./img/u_b04.gif\" align=left hspace=0 vspace=0 border=0>\r\n");
      out.write("                				</td>\r\n");
      out.write("                				<td align=center></td>\r\n");
      out.write("                				<td valign=bottom>\r\n");
      out.write("                  					<img src=\"./img/u_b05.gif\" align=right hspace=0 vspace=0 border=0>\r\n");
      out.write("                				</td>\r\n");
      out.write("              				</tr>\r\n");
      out.write("              				<tr bgcolor=#ffffff>\r\n");
      out.write("                				<td colspan=3 align=center>\r\n");
      out.write("                  					<a href=\"javascript:send()\"><img src=\"./img/u_bt06.gif\" vspace=3 border=0 name=img3></a>\r\n");
      out.write("                  					<a herf=\"javascript:reset()\"><img src=\"./img/u_bt05.gif\" border=0 hspace=10 vspace=3 name=img4></a>\r\n");
      out.write("                				</td>\r\n");
      out.write("              				</tr>\r\n");
      out.write("            			</table> \r\n");
      out.write("          			</td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("      		</td>\r\n");
      out.write("    	</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write(" <!-- copyright 영역 삽입-->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
