/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-19 02:32:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Include/topmenu.jsp", Long.valueOf(1634610601167L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" <head><title>Web Programming Test</title>\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"/stylesheet.css\">\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("   .menu, td {font-size:9pt;}\r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write(" <body text=\"black\" link=\"blue\" vlink=\"purple\" alink=\"red\" bgcolor=\"white\" topmargin=\"0\" leftmargin=\"0\">\r\n");
      out.write(" <table border=\"0\" cellspacing=\"2\" bgcolor=\"#ecf1ef\" width=\"900\" bordercolordark=\"#ffffff\" bordercolorlight=\"#000000\">\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td width=\"20%\" rowspan=\"4\" valign=\"bottom\" bgcolor=\"#000000\">\r\n");
      out.write("       <a href=\"/index.jsp\"><img src=\"/Include/img/ceo.jpg\" width=\"158\" height=\"83\" border=\"0\"></a>\r\n");
      out.write("       <font style=\"font-size:9pt;color:white;font-family:돋움\"><b>Total 136,489\r\n");
      out.write("       <font color=\"yellow\"></font>\r\n");
      out.write("       | Now 178\r\n");
      out.write("       <font color=\"yellow\"></font>\r\n");
      out.write("       </b></font>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" height=\"25\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Users/user_login.jsp\" class=\"white\">로그인</A></b></font></p>\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"\" class=\"white\">로그아웃</A></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Users/user_insert.jsp\" class=\"white\">회원가입</a></b></font></p>\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Users/user_modify.jsp\" class=\"white\">정보수정</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Notice/notice_list.jsp\" class=\"white\">공지사항</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Board/board_list.jsp\" class=\"white\">게시판</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Pds/pds_list.jsp\" class=\"white\">자료실</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Guest/guest_list.jsp\" class=\"white\">방명록</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b>겔러리</b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Admin/admin_login.jsp\" class=\"white\">관리자</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>                   \r\n");
      out.write("   <tr>\r\n");
      out.write("     <td colspan=\"8\">\r\n");
      out.write("     <p><img src=\"/Include/img/bar-01.gif\" width=\"100%\" height=\"1\" border=\"0\"></p>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td colspan=\"8\"><p><img src=\"/Include/img/bar-01.gif\" width=\"100%\" height=\"1\" border=\"0\"></p></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td><p><b><span style=\"font-size:15pt;\">&nbsp;Search</span></b></p></td>\r\n");
      out.write("     <form action=\"\" method=\"post\">\r\n");
      out.write("     <td colspan=\"5\">\r\n");
      out.write("     <p>&nbsp;\r\n");
      out.write("       <Select name=\"genre\" size=\"1\">\r\n");
      out.write("         <option value=\"종합\">공지사항\r\n");
      out.write("         <option value=\"종합\">게시판\r\n");
      out.write("         <option value=\"종합\">방명록\r\n");
      out.write("         <option value=\"종합\">자료실\r\n");
      out.write("       </Select>\r\n");
      out.write("       <Select name=\"item\" size=\"1\">\r\n");
      out.write("         <option value=\"name\">작성자\r\n");
      out.write("         <option value=\"subject\">제목\r\n");
      out.write("         <option value=\"contents\">제목\r\n");
      out.write("       </Select>\r\n");
      out.write("         <input type=\"text\" name=\"keyword\" size=\"12\">\r\n");
      out.write("         <input type=\"image\" src=\"/Include/img/search2.gif\">\r\n");
      out.write("     </td>\r\n");
      out.write("     </form>\r\n");
      out.write("   </tr>\r\n");
      out.write(" </table>  \r\n");
      out.write(" </body>\r\n");
      out.write(" </html>\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>로그온</TITLE>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<STYLE TYPE=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body { font-family: 돋움, Verdana; font-size: 9pt}\r\n");
      out.write("td   { font-family: 돋움, Verdana; font-size: 9pt; text-decoration: none; color: #000000; \r\n");
      out.write("      BACKGROUND-POSITION: left top; BACKGROUND-REPEAT: no-repeat;}\r\n");
      out.write("//-->\r\n");
      out.write("</STYLE>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" text=\"#000000\" leftmargin=0 \r\n");
      out.write("  topmargin=0 onLoad='document.fname.user_id.focus();'>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" width=\"800\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <td width=\"20%\"  bgcolor=\"#ecf1ef\" valign=\"top\" style=\"padding-left:0;\">\r\n");
      out.write("	<!--로그인 영역 삽입-->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/Include/login_form.jsp", out, false);
      out.write(" \r\n");
      out.write("	 \r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=\"80%\" valign=\"top\">&nbsp;<img src=\"/Users/img/title1.gif\" ><br>    \r\n");
      out.write("<TABLE width=\"683\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" height=\"265\">\r\n");
      out.write("<TR>\r\n");
      out.write("  <TD width=100>&nbsp;</td>\r\n");
      out.write("  <TD>\r\n");
      out.write("    <table width=\"583\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" height=\"265\">\r\n");
      out.write("	  <form name=fname method=post action=\"\"\">\r\n");
      out.write("	    <tr>\r\n");
      out.write("		  <td height=\"298\"> \r\n");
      out.write("		    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("			  <tr> \r\n");
      out.write("			    <td width=\"9\"><img src=\"/Users/img/h_b02.gif\" width=\"9\" height=\"21\"></td>\r\n");
      out.write("				<td bgcolor=\"7aaad5\"> \r\n");
      out.write("				 <div align=\"center\"><font color=\"#FFFFFF\"><b>Member Login</b></font></div>\r\n");
      out.write("				 </td>\r\n");
      out.write("				 <td width=\"9\"><img src=\"/Users/img/f_b03.gif\" width=\"9\" height=\"21\"></td>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			 </table>\r\n");
      out.write("			 <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"550\">\r\n");
      out.write("			   <tr> \r\n");
      out.write("			     <td bgcolor=\"#7aaad5\"> \r\n");
      out.write("				   <table border=\"0\" cellpadding=\"3\" cellspacing=\"1\" width=\"99%\" height=\"321\">\r\n");
      out.write("				     <tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("					   <td align=CENTER bgcolor=\"#eff4f8\" height=\"92\"> \r\n");
      out.write("					     <table width=\"330\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("							<tr valign=bottom> \r\n");
      out.write("							  <td width=\"21\"><img src=\"/Users/img/h_bl02.gif\" width=\"18\" height=\"16\"></td>\r\n");
      out.write("							  <td width=\"55\" nowrap>아 이 디</td>\r\n");
      out.write("							  <td width=\"175\">: \r\n");
      out.write("								<input type=text name=\"userid\" size=16 maxlength=16 STYLE=\"WIDTH:155\">\r\n");
      out.write("							  </td>\r\n");
      out.write("							  <td width=\"79\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr valign=bottom> \r\n");
      out.write("							  <td><img src=\"/Users/img/h_bl02.gif\" width=\"18\" height=\"16\"></td>\r\n");
      out.write("							  <td nowrap>비밀번호</td>\r\n");
      out.write("							  <td>: \r\n");
      out.write("								<input type=password name=\"passwd\" size=14 maxlength=12 STYLE=\"WIDTH:155\">\r\n");
      out.write("							  </td>\r\n");
      out.write("							  <td><input type=image src=\"/Users/img/login.gif\" border=0 align=absmiddle></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						  </table>\r\n");
      out.write("						</td>\r\n");
      out.write("					  </tr>\r\n");
      out.write("					  <tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("						<td bgcolor=\"#ffffff\" align=CENTER height=\"138\"> \r\n");
      out.write("							[아이디찾기] &nbsp;&nbsp; [비밀번호찾기]\r\n");
      out.write("						</td>\r\n");
      out.write("					  </tr>\r\n");
      out.write("\r\n");
      out.write("					  <tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("						<td bgcolor=\"#ffffff\" align=CENTER height=\"138\"> \r\n");
      out.write("						  <table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("							<tr> \r\n");
      out.write("							  <td> \r\n");
      out.write("								<table cellpadding=2 cellspacing=0 align=center border=0>\r\n");
      out.write("								  <tr> \r\n");
      out.write("									<td> \r\n");
      out.write("										<p style=\"LINE-HEIGHT:15PX;\"><font color=\"#AFAFB1\">\r\n");
      out.write("										이곳은 JSP를 배우고자 하는 분이면 누구나\r\n");
      out.write("										   <FONT COLOR=\"#006F70\">회원가입 할 수 있는 </FONT>곳입니다.<BR><BR>\r\n");
      out.write("									</td> \r\n");
      out.write("								  </tr> \r\n");
      out.write("					              <tr> \r\n");
      out.write("							        <td> \r\n");
      out.write("							          <p style=\"LINE-HEIGHT:15PX;\"><font color=\"#AFAFB1\">아이디가 \r\n");
      out.write("								      없으신 분은 \r\n");
      out.write("							          <font color=\"#ff7508\">이용자가입</font>을 하시기 바랍니다.<br>\r\n");
      out.write("							            <br>\r\n");
      out.write("							            <br>\r\n");
      out.write("							          </p>\r\n");
      out.write("							       </td>\r\n");
      out.write("							      </tr>\r\n");
      out.write("						         </table>\r\n");
      out.write("						       </td>\r\n");
      out.write("					         </tr>\r\n");
      out.write("					       </table>\r\n");
      out.write("				         </td>\r\n");
      out.write("				       </tr>\r\n");
      out.write("			         </table>\r\n");
      out.write("			  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr> \r\n");
      out.write("				  <td width=\"9\"><img src=\"/Users/img/h_b04.gif\" width=\"12\" height=\"11\"></td>\r\n");
      out.write("				  <td bgcolor=\"7aaad5\" width=\"612\"> \r\n");
      out.write("					<div align=\"center\"></div>\r\n");
      out.write("				  </td>\r\n");
      out.write("				  <td width=\"10\"><img src=\"/Users/img/h_b05.gif\" width=\"12\" height=\"11\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			  </table>\r\n");
      out.write("			</td>\r\n");
      out.write("  		</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
