/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-27 05:58:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userinfo_005finsert_005femail_005fservlet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>이메일 인증을 수행합니다</TITLE>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<STYLE TYPE=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body { font-family: 돋움, Verdana; font-size: 9pt}\r\n");
      out.write("td   { font-family: 돋움, Verdana; font-size: 9pt; text-decoration: none; color: #000000} \r\n");
      out.write("--->\r\n");
      out.write("</STYLE>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function codeCheck(authNum){\r\n");
      out.write("		if(usermail.emailcode.value == \"\"){\r\n");
      out.write("			alert(\"인증번호을 입력하세요\");\r\n");
      out.write("			usermail.emailcode.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("    	// 입력한 값이 없거나, 인증코드가 일지하지 않을 경우\r\n");
      out.write("		if(usermail.emailcode.value != authNum){\r\n");
      out.write("			alert(\"인증번호가 일치하지 않습니다\");\r\n");
      out.write("			self.close();\r\n");
      out.write("    	// 인증코드가 일치하는 경우\r\n");
      out.write("		}else if(usermail.emailcode.value==authNum){\r\n");
      out.write("			alert(\"인증되었습니다\");\r\n");
      out.write("			self.close();\r\n");
      out.write("			//opener.document.mform.emailconfirm_value.value=1;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY bgcolor=\"#FFFFFF\">\r\n");
      out.write("<TABLE CELLPADDING=0 CELLSPACING=0 BORDER=0 WIDTH=430>\r\n");
      out.write("  <TR BGCOLOR=#7AAAD5>\r\n");
      out.write("    <td align=left><img src=\"./img/u_b02.gif\"></td>\r\n");
      out.write("    <td align=center><FONT COLOR=\"#FFFFFF\"><b>이메일 인증</FONT></td>\r\n");
      out.write("    <td align=right><img src=\"./img/u_b03.gif\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<TABLE CELLPADDING=0 CELLSPACING=0 BORDER=0 WIDTH=430>\r\n");
      out.write("<TR BGCOLOR=#948DCF>\r\n");
      out.write("  <TD>\r\n");
      out.write("  <form method=\"post\" action=\"\" name=\"usermail\">\r\n");
      out.write("    <TABLE CELLPADDING=4 CELLSPACING=1 BORDER=0 WIDTH=430>\r\n");
      out.write("  	  <TR BGCOLOR=\"#FFFFFF\">\r\n");
      out.write("        <TD ALIGN=\"center\">\r\n");
      out.write("          <FONT FACE=\"굴림\"><B>인증번호를 입력하세요</B></FONT><br>\r\n");
      out.write("        </TD>\r\n");
      out.write("        <TD ALIGN=\"center\">\r\n");
      out.write("           <INPUT NAME=\"emailcode\" type=text size=16 maxlength=16>\r\n");
      out.write("      	   <a href=\"javascript:codeCheck('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"><img src=\"./img/u_bt08.gif\" border=0 vspace=0></a>\r\n");
      out.write("        </TD>\r\n");
      out.write("      </TR>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("  </form>  \r\n");
      out.write(" </TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("\r\n");
      out.write("<TABLE CELLPADDING=0 CELLSPACING=0 BORDER=0 WIDTH=430>\r\n");
      out.write("  <TR BGCOLOR=#7AAAD5>\r\n");
      out.write("    <td align=left><img src=\"./img/u_b04.gif\"></td>\r\n");
      out.write("    <td align=right><img src=\"./img/u_b05.gif\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=3 align=center>\r\n");
      out.write("      <a href=\"javascript:self.close()\"><img src=\"./img/u_bt13.gif\" border=0 vspace=5></a>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
