/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-03 02:21:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005finsert_005fajax_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1633479562941L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/eclipse-workspace/WebExamTrack2_4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/exSampleMVC/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/Include/login_form.jsp", Long.valueOf(1634610601165L));
    _jspx_dependants.put("/Include/topmenu.jsp", Long.valueOf(1635905024320L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" <head><title>Web Programming Test</title>\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"/stylesheet.css\">\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("   .menu, td {font-size:9pt;}\r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write(" <body text=\"black\" link=\"blue\" vlink=\"purple\" alink=\"red\" bgcolor=\"white\" topmargin=\"0\" leftmargin=\"0\">\r\n");
      out.write(" <table border=\"0\" cellspacing=\"2\" bgcolor=\"#ecf1ef\" width=\"900\" bordercolordark=\"#ffffff\" bordercolorlight=\"#000000\">\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td width=\"20%\" rowspan=\"4\" valign=\"bottom\" bgcolor=\"#000000\">\r\n");
      out.write("       <a href=\"/index.jsp\"><img src=\"/Include/img/ceo.jpg\" width=\"158\" height=\"83\" border=\"0\"></a>\r\n");
      out.write("       <font style=\"font-size:9pt;color:white;font-family:돋움\"><b>Total 136,489\r\n");
      out.write("       <font color=\"yellow\"></font>\r\n");
      out.write("       | Now 178\r\n");
      out.write("       <font color=\"yellow\"></font>\r\n");
      out.write("       </b></font>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" height=\"25\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write(' ');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Notice?cmd=notice_list\" class=\"white\">공지사항</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Board?cmd=board_list&page=1\" class=\"white\">게시판</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Pds?cmd=pds_list&page=1\" class=\"white\">자료실</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Guest?cmd=guest_list&page=1\" class=\"white\">방명록</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"\" class=\"white\">겔러리</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/Admin/admin_login.jsp\" class=\"white\">관리자</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td bgcolor=\"#9966ff\" width=\"10%\" onmouseover=\"style.backgroundColor='#2772D3'\" onmouseout=\"style.backgroundColor=''\">\r\n");
      out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/User?cmd=user_insert_ajax\" class=\"white\">회원가입</a></b></font></p>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>                   \r\n");
      out.write("   <tr>\r\n");
      out.write("     <td colspan=\"8\">\r\n");
      out.write("     <p><img src=\"/Include/img/bar-01.gif\" width=\"100%\" height=\"1\" border=\"0\"></p>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td colspan=\"8\"><p><img src=\"/Include/img/bar-01.gif\" width=\"100%\" height=\"1\" border=\"0\"></p></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td><p><b><span style=\"font-size:15pt;\">&nbsp;Search</span></b></p></td>\r\n");
      out.write("     <form action=\"\" method=\"post\">\r\n");
      out.write("     <td colspan=\"5\">\r\n");
      out.write("     <p>&nbsp;\r\n");
      out.write("       <Select name=\"genre\" size=\"1\">\r\n");
      out.write("         <option value=\"종합\">공지사항\r\n");
      out.write("         <option value=\"종합\">게시판\r\n");
      out.write("         <option value=\"종합\">방명록\r\n");
      out.write("         <option value=\"종합\">자료실\r\n");
      out.write("       </Select>\r\n");
      out.write("       <Select name=\"item\" size=\"1\">\r\n");
      out.write("         <option value=\"name\">작성자\r\n");
      out.write("         <option value=\"subject\">제목\r\n");
      out.write("         <option value=\"contents\">제목\r\n");
      out.write("       </Select>\r\n");
      out.write("         <input type=\"text\" name=\"keyword\" size=\"12\">\r\n");
      out.write("         <input type=\"image\" src=\"/Include/img/search2.gif\">\r\n");
      out.write("     </td>\r\n");
      out.write("     </form>\r\n");
      out.write("   </tr>\r\n");
      out.write(" </table>  \r\n");
      out.write(" </body>\r\n");
      out.write(" </html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원등록</title>\r\n");
      out.write("<STYLE TYPE=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body { font-family: 돋움, Verdana; font-size: 9pt}\r\n");
      out.write("td   { font-family: 돋움, Verdana; font-size: 9pt; text-decoration: none; color: #000000; BACKGROUND-POSITION: left top; BACKGROUND-REPEAT: no-repeat;}\r\n");
      out.write("-->\r\n");
      out.write(".formbox {\r\n");
      out.write("	BACKGROUND-COLOR: #F0F0F0; FONT-FAMILY: \"Verdana\", \"Arial\", \"Helvetica\", \"돋움\"; FONT-SIZE:9pt\r\n");
      out.write("} \r\n");
      out.write("--->\r\n");
      out.write("</STYLE>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	// input에 입력된 값에 변화가 있을 시\r\n");
      out.write("	// alert로 입력된 값 출력\r\n");
      out.write("	$(\"input[name='userid']\").on(\"change\",function(){\r\n");
      out.write("		var userid=$('#userid').val();\r\n");
      out.write("		//alert(\"userid :\" + userid);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:'/User?cmd=user_idcheck_ajax',  //서블릿 이용시\r\n");
      out.write("			//url:'user_insert_pro.jsp'\r\n");
      out.write("			type:'post',\r\n");
      out.write("			data:{'userid': userid},\r\n");
      out.write("			success:function(result){\r\n");
      out.write("				if(result==0){\r\n");
      out.write("					userid_c.innerHTML=\"사용가능한 아이디입니다\";\r\n");
      out.write("					$('#passwd').focus();\r\n");
      out.write("				}else if(result==1){\r\n");
      out.write("					userid_c.innerHTML=\"중복된 아이디입니다\";\r\n");
      out.write("					$('#userid').val('');\r\n");
      out.write("					$('#userid').focus();\r\n");
      out.write("				}else{\r\n");
      out.write("					userid_c.innerHTML=\"결과\" + result;\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error:function(error){\r\n");
      out.write("				alert(\"error : \" + error);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//비번 체크\r\n");
      out.write("	$(\"input[name='repasswd']\").on(\"change\",function(){\r\n");
      out.write("		var passwd=$('#passwd').val();\r\n");
      out.write("		var repasswd=$('#repasswd').val();\r\n");
      out.write("		//alert(\"userid :\" + userid);\r\n");
      out.write("		if(passwd!=repasswd){\r\n");
      out.write("			repasswd_c.innerHTML=\"비밀번호를 다시 입력하세요\";\r\n");
      out.write("			$('#repasswd').val('');\r\n");
      out.write("			$('#repasswd').focus();\r\n");
      out.write("		}else if(passwd==repasswd){\r\n");
      out.write("			repasswd_c.innerHTML=\"확인되었습니다\";\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	function send(){\r\n");
      out.write("		if(user.name.value==\"\"){\r\n");
      out.write("			alert(\"이름을 입력하세요\");\r\n");
      out.write("			user.name.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		user.action=\"Users?cmd=user_insert_pro\";\r\n");
      out.write("		user.submit();\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	//아이디 중복검사 함수\r\n");
      out.write("	function idCheck(){\r\n");
      out.write("		window.open(\"/Users?cmd=user_idcheck\",\"아이디중복검삭\",\"width=350 height=250\");	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//keyPress\r\n");
      out.write("	function passCheck1(){\r\n");
      out.write("		if(event.keyCode==13){\r\n");
      out.write("			user.repasswd.focus();\r\n");
      out.write("		}	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function passCheck2(){\r\n");
      out.write("		if(user.passwd.value != user.repasswd.value){\r\n");
      out.write("			alert(\"오류\");\r\n");
      out.write("			user.repasswd.focus();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function emailCheck(){\r\n");
      out.write("		if(user.email3.selectedIndex==0){\r\n");
      out.write("			user.email2.readOnly=false;\r\n");
      out.write("			user.email2.value=\"\";\r\n");
      out.write("			user.email2.focus();\r\n");
      out.write("		}else{\r\n");
      out.write("			user.email2.readOnly=true;\r\n");
      out.write("			user.email2.value=user.email3.value;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function emailCheck2(){\r\n");
      out.write("		if(user.email3.selectedIndex==0){\r\n");
      out.write("			user.email2.readOnly=false;\r\n");
      out.write("			user.email2.value=\"\";\r\n");
      out.write("			user.email2.focus();\r\n");
      out.write("		}else{\r\n");
      out.write("			user.email2.readOnly=true;\r\n");
      out.write("			user.email2.value=user.email3.value;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var url=\"/User?cmd=user_email_check&email1=\"+user.email1.value+\"&email2=\"+user.email2.value;\r\n");
      out.write("		window.open(url,\"메일인증\",\"width=450, height=200\");\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" LEFTMARGIN=0  TOPMARGIN=0 >\r\n");
      out.write(" <table border=\"0\" width=\"800\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <td width=\"20%\"  bgcolor=\"#ecf1ef\" valign=\"top\" style=\"padding-left:0;\">\r\n");
      out.write("	\r\n");
      out.write("	<!--로그인 영역 삽입-->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <title>Login</title>\r\n");
      out.write("\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write(" \r\n");
      out.write("   <table width=\"100%\" height=\"120\" border=\"0\">\r\n");
      out.write("   <form name=\"login_form\" action=\"\" method=\"post\" >\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td colspan=\"2\" bgcolor=\"#6FA0E\" height=\"20\" align=\"center\">\r\n");
      out.write("         <font size=\"2\" color=\"white\"><b>Member Login</b></font>\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td ><font size=\"2\">아 이 디</font></td>\r\n");
      out.write("       <td ><input type=\"text\" size=\"10\" name=\"userid\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td><font size=\"2\">비밀번호</font></td>\r\n");
      out.write("			 <td>\r\n");
      out.write("         <input type=\"password\" size=\"10\" name=\"passwd\">\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td><input type=\"image\" src=\"/Include/img/login1.gif\" border=\"0\" onClick=\"return check_login()\"></td>\r\n");
      out.write("			 <td>\r\n");
      out.write("           <a href=\"\"><img src=\"/Include/img/regist.gif\" border=\"0\"></a>\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write(" </form>\r\n");
      out.write(" </table>\r\n");
      out.write(" \r\n");
      out.write(" <table width=\"100%\" height=\"120\" border=\"0\">\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td bgcolor=\"#6FA0E\" align=\"center\" height=\"20\">\r\n");
      out.write("       <font size=\"2\" color=\"white\">홍길동 님!</font>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td align=\"center\">\r\n");
      out.write("       <font size=\"2\">\r\n");
      out.write("       <a href=\"adminpage.jsp\">관리자 페이지</a><br>\r\n");
      out.write("       <a href=\"logout.jsp\">로그오프</a><br>\r\n");
      out.write("       <a href=\"userinfo_view.jsp\">회원정보수정</a><br>\r\n");
      out.write("       </font>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write(" </table>\r\n");
      out.write(" \r\n");
      out.write(" <table width=\"100%\" height=\"120\" border=\"0\">\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td bgcolor=\"#6FA0E\" align=\"center\" height=\"20\">\r\n");
      out.write("       <font size=\"2\" color=\"white\">홍길동민 님!</font>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td align=\"center\">\r\n");
      out.write("       <font size=\"2\">\r\n");
      out.write("       <a href=\"logout.jsp\">로그오프</a><br>\r\n");
      out.write("       <a href=\"userinfo_view.jsp\">회원정보수정</a>\r\n");
      out.write("       <a href=\"userinfo_del.jsp\">회원탈퇴</a>\r\n");
      out.write("\r\n");
      out.write("       </font>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write(" </table>\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write(" </html>\r\n");
      out.write("\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=\"80%\" valign=\"top\">&nbsp;<img src=\"/Users/img/title1.gif\" ><br>    \r\n");
      out.write("	<form name=\"user\" method=post>\r\n");
      out.write("	<table border=0 cellpadding=0 cellspacing=0 border=0 width=730 valign=top>\r\n");
      out.write("		<tr><td align=center><br>                            \r\n");
      out.write("			<table cellpadding=0 cellspacing=0 border=0 width=650 align=center>       \r\n");
      out.write("				<tr>\r\n");
      out.write("					<td bgcolor=\"#7AAAD5\">            \r\n");
      out.write("						<table cellpadding=0 cellspacing=0 border=0 width=100%>\r\n");
      out.write("							<tr bgcolor=#7AAAD5>\r\n");
      out.write("								<td align=left BORDER=\"0\" HSPACE=\"0\" VSPACE=\"0\"><img src=\"/Users/img/u_b02.gif\"></td>\r\n");
      out.write("								<td align=center bgcolor=\"#7AAAD5\"><FONT COLOR=\"#FFFFFF\"><b>사용자등록&nbsp;</b><font color=black>(</font><font color=red>&nbsp;*&nbsp;</font><font color=black>표시항목은 반드시 입력하십시요.)</font></FONT></td>\r\n");
      out.write("								<td align=right BORDER=\"0\" HSPACE=\"0\" VSPACE=\"0\"><img src=\"/Users/img/u_b03.gif\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<table cellpadding=3 cellspacing=1 border=0 width=100%>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td width=110 bgcolor=#EFF4F8>&nbsp;회원 성명<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<input type=text name=name size=16 maxlength=20 value=\"\">성명은 빈칸없이 입력하세요.\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;회원 ID<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<table cellspacing=0 cellpadding=0>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td align=absmiddle>\r\n");
      out.write("												<input type=text id=userid name=userid size=12 maxlength=16 value=\"\" style=\"width:120\">\r\n");
      out.write("											</td>\r\n");
      out.write("											<td id=\"userid_c\">\r\n");
      out.write("                  								[5~16자 이내의 영문이나 숫자만 가능합니다]\r\n");
      out.write("                  							</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</table>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;비밀번호<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("								<input type=password id=passwd name=passwd size=8 maxlength=12 style=\"width:80\" onKeyPress=\"passCheck1()\">\r\n");
      out.write("									6~12자 이내의 영문이나 숫자만 가능합니다.\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;비밀번호확인<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE><input type=password id=repasswd name=repasswd size=8 onFocusOut=\"passCheck2()\" maxlength=12 value=\"\" style=\"width:80\">\r\n");
      out.write("									<font id=\"repasswd_c\" color=red>비밀번호 확인을 위해서 비밀번호를 한번 더 입력해주세요. </font>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;전화번호<font color=red>&nbsp;*</font></td>\r\n");
      out.write("								<TD BGCOLOR=WHITE>\r\n");
      out.write("									<input type=text name=tel size=13 maxlength=13 value=\"\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<TD BGCOLOR=\"#EFF4F8\">&nbsp;E-mail\r\n");
      out.write("                					<font color=red>&nbsp;</font>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td bgcolor=WHITE valign=middle>\r\n");
      out.write("									<input type=\"text\" name=\"email1\" maxlength=\"15\">\r\n");
      out.write("									@ <input type=\"text\" name=\"email2\" maxlength=\"15\">\r\n");
      out.write("									<select name=\"email3\" onChange=\"emailCheck()\">\r\n");
      out.write("		      							<option value=\"0\">직접입력</option>\r\n");
      out.write("		      							<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("		      							<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("		      							<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("		      							<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("		  							   </select>\r\n");
      out.write("									 <input type=\"button\"  value=\"인증하기\" onClick=\"emailCheck2()\">\r\n");
      out.write("									 <input type=\"hidden\"  name=\"flag\" value=\"\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<table cellpadding=0 cellspacing=0 border=0 width=100%>\r\n");
      out.write("							<tr bgcolor=#7AAAD5>\r\n");
      out.write("								<td valign=bottom>\r\n");
      out.write("									<img src=\"/Users/img/u_b04.gif\" align=left hspace=0 vspace=0 border=0 >\r\n");
      out.write("								</td>\r\n");
      out.write("								<td align=center></td>\r\n");
      out.write("								<td valign=bottom>\r\n");
      out.write("									<img src=\"/Users/img/u_b05.gif\" align=right hspace=0 vspace=0 border=0>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr bgcolor=#ffffff>\r\n");
      out.write("								<td colspan=3 align=center>\r\n");
      out.write("									<img src=\"/Users/img/u_bt06.gif\" vspace=3 border=0 name=img3 onClick=\"send()\">\r\n");
      out.write("									<img src=\"/Users/img/u_bt05.gif\" border=0 hspace=10 vspace=3 name=img4 onClick=\"reset()\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table> \r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write(" <!-- copyright 영역 삽입-->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Include/topmenu.jsp(23,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("         \r\n");
          out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/User?cmd=user_login\" class=\"white\">로그인</A></b></font></p>\r\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /Include/topmenu.jsp(26,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("         \r\n");
          out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/User?cmd=user_logout\" class=\"white\">로그아웃</A></b></font></p>\r\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /Include/topmenu.jsp(31,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("              \r\n");
          out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/User?cmd=user_insert\" class=\"white\">회원가입</a></b></font></p>\r\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /Include/topmenu.jsp(34,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("              \r\n");
          out.write("     <p align=\"center\"><font color=\"white\" size=\"2\"><b><a href=\"/User?cmd=user_modify\" class=\"white\">정보수정</a></b></font></p>\r\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
